[package]
name = "ethercrab-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
ethercrab = "0.4.2"
env_logger = "0.11.3"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros", "time", "sync"] }
log = "0.4.21"
signal-hook = "0.3.17"
